#!/usr/bin/env sh

# Include
. "$(dirname "$0")/../shared.sh"

echo "~~ Configuring MySQL ~~"

# Create directory's
mkdir -p "${MYSQL_DATA_DIR}"    && chown -R "${MYSQL_USER}":"${MYSQL_GROUP}" "${MYSQL_DATA_DIR}"
mkdir -p "${MYSQL_SOCKET%/*}"   && chown -R "${MYSQL_USER}":"${MYSQL_GROUP}" "${MYSQL_SOCKET%/*}"
mkdir -p "${MYSQL_PID_FILE%/*}" && chown -R "${MYSQL_USER}":"${MYSQL_GROUP}" "${MYSQL_PID_FILE%/*}"

# set my.cnf variables
MYSQL_CNF="/etc/mysql/my.cnf"
replaceInFile "\@MYSQL_DATA_DIR\@" "${MYSQL_DATA_DIR}" "${MYSQL_CNF}"
replaceInFile "\@MYSQL_PORT\@" "${MYSQL_PORT}" "${MYSQL_CNF}"
replaceInFile "\@MYSQL_SOCKET\@" "${MYSQL_SOCKET}" "${MYSQL_CNF}"

# PHP ini file
PHP5_INI="/etc/php5/php.ini"
replaceInFile "\@MYSQL_DATA_DIR\@" "${MYSQL_DATA_DIR}" "${PHP5_INI}"
replaceInFile "\@MYSQL_PORT\@" "${MYSQL_PORT}" "${PHP5_INI}"
replaceInFile "\@MYSQL_SOCKET\@" "${MYSQL_SOCKET}" "${PHP5_INI}"
